server:
  port: 8090
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    generate-unique-name: false
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    generate-ddl: true
    defer-datasource-initialization: true
    database: h2